// This file is generated by scripts/generate-api-client.mjs.
// Do not edit it directly. Run pnpm client:generate after changing OpenAPI.

export type ProjectStatus =
  'draft' | 'open' | 'on_hold' | 'closed' | 'cancelled';
export type RecruitmentStatus = 'recruiting' | 'paused' | 'filled' | 'ended';

export interface AuthContext {
  requiresMfa: boolean;
}

export interface Project {
  id: string;
  managementNo: string;
  projectName: string;
  summary: string | null;
  projectStatus: ProjectStatus;
  recruitmentStatus: RecruitmentStatus;
  plannedStartOn: string | null;
  plannedEndOn: string | null;
  updatedAt: string;
  rowVersion: number;
}

export interface ProjectList {
  items: Project[];
  page: { limit: number; nextCursor: string | null };
}

export interface ProjectAuditEvent {
  id: string;
  occurredAt: string;
  actorUserId: string | null;
  action: string;
  requestId: string | null;
}

export interface ProjectAuditList {
  items: ProjectAuditEvent[];
}

export interface ProjectInput {
  managementNo: string;
  projectName: string;
  summary: string | null;
  projectStatus: ProjectStatus;
  recruitmentStatus: RecruitmentStatus;
  plannedStartOn: string | null;
  plannedEndOn: string | null;
}

export interface ApiErrorBody {
  error: { code: string; message: string; requestId: string };
}

export interface ListProjectsQuery {
  q?: string;
  status?: ProjectStatus;
  recruitmentStatus?: RecruitmentStatus;
  cursor?: string;
  limit?: number;
}
