// This file is generated by scripts/generate-api-client.mjs.
// Do not edit it directly. Run pnpm client:generate after changing OpenAPI.

export type ProjectStatus =
  'draft' | 'open' | 'on_hold' | 'closed' | 'cancelled';
export type RecruitmentStatus = 'recruiting' | 'paused' | 'filled' | 'ended';
export type CompanyStatus = 'prospect' | 'active' | 'inactive' | 'blocked';
export type ContactStatus = 'active' | 'inactive' | 'left_company' | 'unknown';
export type EngineerStatus =
  'candidate' | 'active' | 'inactive' | 'retired' | 'blocked';
export type AvailabilityStatus =
  'unknown' | 'available' | 'proposed' | 'engaged' | 'unavailable';
export type ProposalStatus =
  | 'draft'
  | 'pending_approval'
  | 'approved'
  | 'sent'
  | 'interview_requested'
  | 'interviewing'
  | 'offered'
  | 'won'
  | 'lost'
  | 'withdrawn'
  | 'cancelled';
export type InterviewType = 'online' | 'onsite' | 'phone' | 'other';
export type InterviewStatus =
  'tentative' | 'scheduled' | 'completed' | 'cancelled' | 'no_show';
export type ContractType =
  | 'ses'
  | 'dispatch'
  | 'subcontract'
  | 'quasi_mandate'
  | 'fixed_price'
  | 'other';
export type ContractStatus =
  | 'draft'
  | 'review'
  | 'active'
  | 'suspended'
  | 'expired'
  | 'terminated'
  | 'cancelled';
export type EngagementStatus =
  'draft' | 'preparing' | 'active' | 'ending' | 'ended' | 'cancelled';
export type WorkLogStatus =
  'draft' | 'submitted' | 'approved' | 'rejected' | 'locked';
export type WorkType =
  'work' | 'paid_leave' | 'absence' | 'holiday' | 'training' | 'other';
export type InvoiceStatus =
  | 'draft'
  | 'issued'
  | 'sent'
  | 'partially_paid'
  | 'paid'
  | 'overdue'
  | 'cancelled'
  | 'void';
export type InvoiceType = 'sales' | 'purchase';
export type AccountingCloseStatus = 'open' | 'closed';
export type AccountingCloseType = 'sales' | 'invoice' | 'payment';

export interface AuthContext {
  requiresMfa: boolean;
}

export interface Engineer {
  id: string;
  managementNo: string;
  familyName: string;
  givenName: string;
  displayName: string | null;
  status: EngineerStatus;
  availabilityStatus: AvailabilityStatus;
  availableFrom: string | null;
  nearestStation: string | null;
  summary: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface EngineerList {
  items: Engineer[];
  page: { limit: number; nextCursor: string | null };
}
export interface EngineerInput {
  managementNo: string;
  familyName: string;
  givenName: string;
  displayName: string | null;
  status: EngineerStatus;
  availabilityStatus: AvailabilityStatus;
  availableFrom: string | null;
  nearestStation: string | null;
  summary: string | null;
}
export interface EngineerAuditEvent {
  id: string;
  occurredAt: string;
  actorUserId: string | null;
  action: string;
  requestId: string | null;
}
export interface EngineerAuditList {
  items: EngineerAuditEvent[];
}
export type EngineerGender = 'male' | 'female' | 'other' | 'undisclosed';
export interface EngineerPrivateDetail {
  engineerId: string;
  birthDate: string | null;
  gender: EngineerGender | null;
  personalEmail: string | null;
  phone: string | null;
  postalCode: string | null;
  prefecture: string | null;
  city: string | null;
  addressLine: string | null;
  emergencyContact: string | null;
  notes: string | null;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerPrivateInput = Omit<
  EngineerPrivateDetail,
  'engineerId' | 'updatedAt' | 'rowVersion'
>;
export type EngineerAffiliationType =
  'employee' | 'freelance' | 'partner_employee' | 'subcontractor' | 'other';
export interface EngineerAffiliation {
  id: string;
  engineerId: string;
  companyId: string;
  affiliationType: EngineerAffiliationType;
  contractType: string | null;
  startDate: string;
  endDate: string | null;
  isPrimary: boolean;
  notes: string | null;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerAffiliationInput = Omit<
  EngineerAffiliation,
  'id' | 'engineerId' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerAffiliationList {
  items: EngineerAffiliation[];
}
export type RemotePreference = 'onsite' | 'hybrid' | 'remote' | 'flexible';
export interface EngineerPreference {
  id: string;
  engineerId: string;
  effectiveFrom: string;
  effectiveTo: string | null;
  desiredRateMin: number | null;
  desiredRateMax: number | null;
  currencyCode: string;
  remotePreference: RemotePreference;
  weeklyDaysMin: number | null;
  weeklyDaysMax: number | null;
  overtimeLimitHours: number | null;
  availableFrom: string | null;
  notes: string | null;
  locations: string[];
  contractTypes: string[];
  updatedAt: string;
  rowVersion: number;
}
export type EngineerPreferenceInput = Omit<
  EngineerPreference,
  'id' | 'engineerId' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerPreferenceList {
  items: EngineerPreference[];
}
export interface EngineerCareerHistory {
  id: string;
  engineerId: string;
  projectName: string;
  clientName: string | null;
  roleName: string | null;
  industry: string | null;
  overview: string | null;
  responsibilities: string | null;
  achievements: string | null;
  teamSize: number | null;
  startedOn: string | null;
  endedOn: string | null;
  displayOrder: number;
  sourceResumeVersionId: string | null;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerCareerHistoryInput = Omit<
  EngineerCareerHistory,
  'id' | 'engineerId' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerCareerHistoryList {
  items: EngineerCareerHistory[];
}
export interface EngineerResumeVersion {
  id: string;
  versionNo: number;
  fileStoragePath: string | null;
  originalFileName: string | null;
  mimeType: string | null;
  fileSizeBytes: number | null;
  fileChecksum: string | null;
  sourceType: string;
  createdAt: string;
}
export interface EngineerResume {
  id: string;
  engineerId: string;
  title: string;
  resumeStatus: string;
  currentVersionId: string | null;
  updatedAt: string;
  rowVersion: number;
  versions: EngineerResumeVersion[];
}
export interface EngineerResumeVersionInput {
  title: string;
  resumeStatus: string;
  fileStoragePath: string | null;
  originalFileName: string | null;
  mimeType: string | null;
  fileSizeBytes: number | null;
  fileChecksum: string | null;
  sourceType: string;
}
export interface EngineerResumeList {
  items: EngineerResume[];
}
export interface ResumeExtractionResult {
  profile: {
    summary: string | null;
    nearestStation: string | null;
    availableFrom: string | null;
  };
  careerHistories: Array<{
    projectName: string;
    clientName: string | null;
    roleName: string | null;
    industry: string | null;
    overview: string | null;
    responsibilities: string | null;
    achievements: string | null;
    startedOn: string | null;
    endedOn: string | null;
    evidence: string;
  }>;
  skills: Array<{
    name: string;
    experienceMonths: number | null;
    proficiencyLevel: string | null;
    lastUsedOn: string | null;
    evidence: string;
  }>;
  qualifications: Array<{
    name: string;
    issuer: string | null;
    acquiredOn: string | null;
    expiresOn: string | null;
    evidence: string;
  }>;
  preferences: {
    desiredRoles: string[];
    desiredLocations: string[];
    desiredContractTypes: string[];
    minimumRate: number | null;
    availableFrom: string | null;
  };
  uncertainties: string[];
  confidenceScore: number;
}
export interface ResumeExtraction {
  id: string;
  resumeVersionId: string;
  aiExecutionId: string;
  status:
    'pending' | 'processing' | 'completed' | 'approved' | 'rejected' | 'failed';
  provider: string;
  modelName: string;
  promptVersion: string;
  result: ResumeExtractionResult | null;
  errorMessage: string | null;
  reviewNotes: string | null;
  reviewedAt: string | null;
  createdAt: string;
}
export interface ResumeExtractionReviewInput {
  decision: 'approved' | 'rejected';
  correctedResult: ResumeExtractionResult | null;
  notes: string | null;
}
export interface EngineerSkill {
  id: string;
  engineerId: string;
  skillId: string;
  skillName: string;
  experienceMonths: number | null;
  proficiencyLevel: number | null;
  lastUsedOn: string | null;
  evidenceType: string | null;
  evidenceNote: string | null;
  verificationStatus: string;
  isPrimary: boolean;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerSkillInput = Omit<
  EngineerSkill,
  'id' | 'engineerId' | 'skillName' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerSkillList {
  items: EngineerSkill[];
}
export interface EngineerQualification {
  id: string;
  engineerId: string;
  name: string;
  issuer: string | null;
  credentialId: string | null;
  acquiredOn: string | null;
  expiresOn: string | null;
  notes: string | null;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerQualificationInput = Omit<
  EngineerQualification,
  'id' | 'engineerId' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerQualificationList {
  items: EngineerQualification[];
}
export interface ListEngineersQuery {
  q?: string;
  status?: EngineerStatus;
  availabilityStatus?: AvailabilityStatus;
  cursor?: string;
  limit?: number;
}

export interface Company {
  id: string;
  managementNo: string;
  legalName: string;
  displayName: string | null;
  corporateNumber: string | null;
  postalCode: string | null;
  prefecture: string | null;
  city: string | null;
  addressLine: string | null;
  websiteUrl: string | null;
  representativeName: string | null;
  status: CompanyStatus;
  updatedAt: string;
  rowVersion: number;
}

export interface CompanyList {
  items: Company[];
  page: { limit: number; nextCursor: string | null };
}

export interface CompanyAuditEvent {
  id: string;
  occurredAt: string;
  actorUserId: string | null;
  action: string;
  requestId: string | null;
}

export interface CompanyAuditList {
  items: CompanyAuditEvent[];
}

export interface CompanyInput {
  managementNo: string;
  legalName: string;
  displayName: string | null;
  corporateNumber: string | null;
  postalCode: string | null;
  prefecture: string | null;
  city: string | null;
  addressLine: string | null;
  websiteUrl: string | null;
  representativeName: string | null;
  status: CompanyStatus;
}

export interface ListCompaniesQuery {
  q?: string;
  status?: CompanyStatus;
  cursor?: string;
  limit?: number;
}

export interface CompanyContact {
  id: string;
  companyId: string;
  managementNo: string;
  familyName: string;
  givenName: string | null;
  departmentName: string | null;
  positionTitle: string | null;
  email: string | null;
  phone: string | null;
  mobilePhone: string | null;
  isPrimary: boolean;
  status: ContactStatus;
  updatedAt: string;
  rowVersion: number;
}
export interface CompanyContactList {
  items: CompanyContact[];
  page: { limit: number; nextCursor: string | null };
}
export interface CompanyContactAuditEvent {
  id: string;
  occurredAt: string;
  actorUserId: string | null;
  action: string;
  requestId: string | null;
}
export interface CompanyContactAuditList {
  items: CompanyContactAuditEvent[];
}
export interface CompanyContactInput {
  companyId: string;
  managementNo: string;
  familyName: string;
  givenName: string | null;
  departmentName: string | null;
  positionTitle: string | null;
  email: string | null;
  phone: string | null;
  mobilePhone: string | null;
  isPrimary: boolean;
  status: ContactStatus;
}
export interface ListCompanyContactsQuery {
  companyId?: string;
  q?: string;
  status?: ContactStatus;
  cursor?: string;
  limit?: number;
}

export interface Project {
  id: string;
  managementNo: string;
  projectName: string;
  summary: string | null;
  projectStatus: ProjectStatus;
  recruitmentStatus: RecruitmentStatus;
  plannedStartOn: string | null;
  plannedEndOn: string | null;
  updatedAt: string;
  rowVersion: number;
}

export interface ProjectList {
  items: Project[];
  page: { limit: number; nextCursor: string | null };
}

export interface ProjectAuditEvent {
  id: string;
  occurredAt: string;
  actorUserId: string | null;
  action: string;
  requestId: string | null;
}

export interface ProjectAuditList {
  items: ProjectAuditEvent[];
}

export interface ProjectInput {
  managementNo: string;
  projectName: string;
  summary: string | null;
  projectStatus: ProjectStatus;
  recruitmentStatus: RecruitmentStatus;
  plannedStartOn: string | null;
  plannedEndOn: string | null;
}

export interface ProjectExtractionResult {
  projectName: string | null;
  summary: string | null;
  responsibilities: string | null;
  openings: number | null;
  startOn: string | null;
  endOn: string | null;
  requiredSkills: Array<{
    name: string;
    requiredMonths: number | null;
    evidence: string;
  }>;
  preferredSkills: Array<{
    name: string;
    requiredMonths: number | null;
    evidence: string;
  }>;
  commercial: {
    rateMin: number | null;
    rateMax: number | null;
    currencyCode: string;
    taxTreatment: string | null;
    settlementLowerHours: number | null;
    settlementUpperHours: number | null;
    paymentTermsDays: number | null;
    contractType: string | null;
    commercialFlow: string | null;
    restrictions: string[];
  };
  workConditions: {
    workplace: string | null;
    prefecture: string | null;
    nearestStation: string | null;
    remoteType: 'onsite' | 'hybrid' | 'remote' | 'negotiable' | null;
    remoteDaysPerWeek: number | null;
    workStartTime: string | null;
    workEndTime: string | null;
  };
  interviewCount: number | null;
  interviewScheduleText: string | null;
  companyCandidates: Array<{
    name: string;
    relationType: string | null;
    contactName: string | null;
    evidence: string;
  }>;
  uncertainties: string[];
  confidenceScore: number;
}
export interface ProjectExtraction {
  id: string;
  projectId: string;
  aiExecutionId: string;
  status:
    | 'pending'
    | 'processing'
    | 'completed'
    | 'failed'
    | 'reviewed'
    | 'applied'
    | 'rejected';
  provider: string;
  modelName: string;
  promptVersion: string;
  result: ProjectExtractionResult | null;
  errorMessage: string | null;
  reviewNotes: string | null;
  reviewedAt: string | null;
  appliedAt: string | null;
  createdAt: string;
}
export interface ProjectExtractionReviewInput {
  decision: 'approved' | 'rejected';
  correctedResult: ProjectExtractionResult | null;
  notes: string | null;
}

export interface ApiErrorBody {
  error: { code: string; message: string; requestId: string };
}

export interface ListProjectsQuery {
  q?: string;
  status?: ProjectStatus;
  recruitmentStatus?: RecruitmentStatus;
  cursor?: string;
  limit?: number;
}

export interface ContractSummary {
  id: string;
  contractNo: string;
  projectId: string | null;
  proposalId: string | null;
  engineerId: string | null;
  contractType: ContractType;
  status: ContractStatus;
  title: string;
  startDate: string;
  endDate: string | null;
  autoRenew: boolean;
  currency: string;
  updatedAt: string;
  rowVersion: number;
}
export type ContractPartyRole =
  | 'customer'
  | 'supplier'
  | 'employer'
  | 'end_client'
  | 'prime_contractor'
  | 'subcontractor'
  | 'other';
export type ContractBillingRole = 'bill_to' | 'pay_to' | 'none';
export interface ContractParty {
  id: string;
  companyId: string;
  contactId: string | null;
  partyRole: ContractPartyRole;
  billingRole: ContractBillingRole | null;
  isPrimary: boolean;
}
export type ContractPartyInput = Omit<ContractParty, 'id'>;
export type ContractApprovalStatus =
  'draft' | 'pending' | 'approved' | 'rejected' | 'cancelled' | 'expired';
export interface ContractApproval {
  id: string;
  status: ContractApprovalStatus;
  requestedAt: string | null;
  completedAt: string | null;
  requestNote: string | null;
  decisionNote: string | null;
  rowVersion: number;
}
export interface ContractVersion {
  id: string;
  versionNo: number;
  effectiveFrom: string;
  effectiveTo: string | null;
  changeSummary: string | null;
  approvedAt: string | null;
  createdAt: string;
}
export type ContractWorkLogStatus =
  'draft' | 'submitted' | 'approved' | 'rejected' | 'locked';
export interface ContractWorkLog {
  id: string;
  engineerId: string;
  workMonth: string;
  status: ContractWorkLogStatus;
  scheduledDays: number | null;
  actualDays: number | null;
  scheduledHours: number | null;
  actualHours: number | null;
  overtimeHours: number;
  absenceHours: number;
  customerApprovedAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface Contract extends ContractSummary {
  monthlyAmount: number | null;
  hourlyAmount: number | null;
  settlementLowerHours: number | null;
  settlementUpperHours: number | null;
  paymentTerms: string | null;
  notes: string | null;
  parties: ContractParty[];
  versions: ContractVersion[];
  workLogs: ContractWorkLog[];
  approval: ContractApproval | null;
}
export interface ContractInput {
  contractNo: string;
  projectId: string | null;
  proposalId: string | null;
  engineerId: string | null;
  contractType: ContractType;
  title: string;
  startDate: string;
  endDate: string | null;
  autoRenew: boolean;
  currency: string;
  monthlyAmount: number | null;
  hourlyAmount: number | null;
  settlementLowerHours: number | null;
  settlementUpperHours: number | null;
  paymentTerms: string | null;
  notes: string | null;
  parties: ContractPartyInput[];
  changeSummary: string | null;
}
export interface ContractStatusTransitionInput {
  status: 'draft' | 'review' | 'active';
  reason: string | null;
}
export interface ContractList {
  items: ContractSummary[];
  page: { limit: number; nextCursor: string | null };
}
export interface ListContractsQuery {
  q?: string;
  status?: ContractStatus;
  cursor?: string;
  limit?: number;
}

export interface WorkLogSummary {
  id: string;
  contractId: string;
  engineerId: string;
  contractTitle: string;
  engineerName: string;
  workMonth: string;
  status: WorkLogStatus;
  scheduledDays: number | null;
  actualDays: number | null;
  scheduledHours: number | null;
  actualHours: number | null;
  overtimeHours: number;
  absenceHours: number;
  customerApprovedAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface WorkLogDetailItem {
  id: string;
  workDate: string;
  workType: WorkType;
  startTime: string | null;
  endTime: string | null;
  breakMinutes: number;
  workHours: number;
  overtimeHours: number;
  description: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface WorkLog extends WorkLogSummary {
  approvedByName: string | null;
  notes: string | null;
  details: WorkLogDetailItem[];
  statusHistories: WorkLogStatusHistory[];
  approval: WorkLogApproval | null;
}
export interface WorkLogStatusHistory {
  id: string;
  fromStatus: WorkLogStatus | null;
  toStatus: WorkLogStatus;
  changeReason: string | null;
  changedAt: string;
}
export interface WorkLogApproval {
  id: string;
  status: 'pending' | 'approved' | 'rejected';
  requestedAt: string | null;
  completedAt: string | null;
  requestNote: string | null;
  decisionNote: string | null;
}
export interface WorkLogDetailInput {
  workDate: string;
  workType: WorkType;
  startTime: string | null;
  endTime: string | null;
  breakMinutes: number;
  workHours: number;
  overtimeHours: number;
  description: string | null;
}
export interface WorkLogInput {
  contractId: string;
  engineerId: string;
  workMonth: string;
  scheduledDays: number | null;
  scheduledHours: number | null;
  absenceHours: number;
  notes: string | null;
  details: WorkLogDetailInput[];
}
export interface WorkLogStatusTransitionInput {
  status: Exclude<WorkLogStatus, 'draft'>;
  reason: string | null;
  approvedByName: string | null;
}
export interface WorkLogList {
  items: WorkLogSummary[];
  page: { limit: number; nextCursor: string | null };
}
export interface ListWorkLogsQuery {
  q?: string;
  status?: WorkLogStatus;
  workMonth?: string;
  cursor?: string;
  limit?: number;
}

export interface SalesKpiMonth {
  periodMonth: string;
  proposalCount: number;
  interviewProposalCount: number;
  interviewRate: number | null;
  wonCount: number;
  winRate: number | null;
}
export interface ExpiringContract {
  id: string;
  contractNo: string;
  title: string;
  endDate: string;
  daysRemaining: number;
  status: string;
}
export interface SalesKpiDashboard {
  fromDate: string;
  toDate: string;
  contractExpiryDays: number;
  proposalCount: number;
  interviewProposalCount: number;
  interviewRate: number | null;
  wonCount: number;
  winRate: number | null;
  averageProposalDays: number | null;
  averageInterviewCount: number | null;
  activeProposalCount: number;
  pendingApprovalCount: number;
  scheduledInterviewCount: number;
  expiringContractCount: number;
  monthly: SalesKpiMonth[];
  expiringContracts: ExpiringContract[];
}
export interface SalesKpiQuery {
  fromDate: string;
  toDate: string;
  contractExpiryDays?: number;
}

export interface ProfitabilityMonth {
  periodMonth: string;
  revenue: number;
  purchaseCost: number;
  expenseCost: number;
  grossProfit: number;
  grossMarginRate: number | null;
  cashIn: number;
  cashOut: number;
  receivableBalance: number;
  payableBalance: number;
  salesInvoiceCount: number;
  purchaseInvoiceCount: number;
  expenseCount: number;
}
export interface ProfitabilityDashboard {
  fromMonth: string;
  toMonth: string;
  currency: string;
  revenue: number;
  purchaseCost: number;
  expenseCost: number;
  grossProfit: number;
  grossMarginRate: number | null;
  cashIn: number;
  cashOut: number;
  receivableBalance: number;
  payableBalance: number;
  monthly: ProfitabilityMonth[];
}
export interface ProfitabilityQuery {
  fromMonth: string;
  toMonth: string;
  currency?: string;
}

export type ExpenseType =
  | 'transportation'
  | 'lodging'
  | 'communication'
  | 'equipment'
  | 'meal'
  | 'other';
export type ExpenseStatus =
  | 'draft'
  | 'submitted'
  | 'approved'
  | 'rejected'
  | 'invoiced'
  | 'reimbursed'
  | 'cancelled';
export interface ExpenseSummary {
  id: string;
  contractId: string | null;
  workLogId: string | null;
  engineerId: string | null;
  contractNo: string | null;
  contractTitle: string | null;
  engineerName: string | null;
  expenseDate: string;
  expenseType: ExpenseType;
  description: string;
  amount: number;
  taxAmount: number;
  currency: string;
  status: ExpenseStatus;
  billable: boolean;
  invoiceId: string | null;
  approvedAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface ExpenseStatusHistory {
  id: string;
  fromStatus: ExpenseStatus | null;
  toStatus: ExpenseStatus;
  changeReason: string | null;
  changedAt: string;
}
export interface ExpenseApproval {
  id: string;
  status:
    'draft' | 'pending' | 'approved' | 'rejected' | 'cancelled' | 'expired';
  requestedAt: string | null;
  completedAt: string | null;
  requestNote: string | null;
  decisionNote: string | null;
}
export interface Expense extends ExpenseSummary {
  receiptPath: string | null;
  notes: string | null;
  statusHistories: ExpenseStatusHistory[];
  approval: ExpenseApproval | null;
}
export interface ExpenseList {
  items: ExpenseSummary[];
}
export interface ListExpensesQuery {
  q?: string;
  status?: ExpenseStatus;
  dateFrom?: string;
  dateTo?: string;
  limit?: number;
}
export interface ExpenseInput {
  contractId: string | null;
  workLogId: string | null;
  engineerId: string | null;
  expenseDate: string;
  expenseType: ExpenseType;
  description: string;
  amount: number;
  taxAmount: number;
  currency: string;
  billable: boolean;
  receiptPath: string | null;
  notes: string | null;
}
export interface ExpenseStatusTransitionInput {
  status: ExpenseStatus;
  reason: string | null;
}

export interface AccountingPeriodSummary {
  id: string;
  periodMonth: string;
  salesStatus: AccountingCloseStatus;
  invoiceStatus: AccountingCloseStatus;
  paymentStatus: AccountingCloseStatus;
  salesClosedAt: string | null;
  invoiceClosedAt: string | null;
  paymentClosedAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface AccountingPeriod extends AccountingPeriodSummary {
  statusHistories: AccountingPeriodStatusHistory[];
}
export interface AccountingPeriodStatusHistory {
  id: string;
  closeType: AccountingCloseType;
  fromStatus: AccountingCloseStatus;
  toStatus: AccountingCloseStatus;
  changeReason: string | null;
  impactConfirmed: boolean;
  changedAt: string;
  changedBy: string | null;
}
export interface AccountingPeriodList {
  items: AccountingPeriodSummary[];
}
export interface ListAccountingPeriodsQuery {
  fromMonth?: string;
  toMonth?: string;
  limit?: number;
}
export interface AccountingPeriodInput {
  periodMonth: string;
}
export interface AccountingPeriodTransitionInput {
  closeType: AccountingCloseType;
  status: AccountingCloseStatus;
  reason: string | null;
  impactConfirmed: boolean;
}

export type AccountingExportFormat =
  'generic_csv' | 'freee' | 'money_forward' | 'yayoi';
export type AccountingExportStatus = 'generated' | 'exported' | 'cancelled';
export interface AccountingExportBatchSummary {
  id: string;
  accountingPeriodId: string;
  periodMonth: string;
  versionNo: number;
  exportFormat: AccountingExportFormat;
  status: AccountingExportStatus;
  generatedAt: string;
  exportedAt: string | null;
  exportReference: string | null;
  lineCount: number;
  debitTotal: number;
  creditTotal: number;
  updatedAt: string;
  rowVersion: number;
}
export interface AccountingExportLine {
  id: string;
  lineNo: number;
  entryDate: string;
  accountCode: string;
  accountName: string;
  debitAmount: number;
  creditAmount: number;
  currency: string;
  description: string;
  sourceType: 'invoice' | 'payment';
  sourceId: string;
}
export interface AccountingExportBatch extends AccountingExportBatchSummary {
  lines: AccountingExportLine[];
}
export interface AccountingExportList {
  items: AccountingExportBatchSummary[];
}
export interface ListAccountingExportsQuery {
  accountingPeriodId?: string;
  limit?: number;
}
export interface AccountingExportGenerateInput {
  accountingPeriodId: string;
  exportFormat: AccountingExportFormat;
}
export interface AccountingExportCompletionInput {
  exportReference: string | null;
}

export interface InvoiceSummary {
  id: string;
  invoiceNo: string;
  invoiceType: InvoiceType;
  contractId: string | null;
  contractTitle: string | null;
  billingCompanyId: string;
  billingCompanyName: string;
  billingPeriodStart: string | null;
  billingPeriodEnd: string | null;
  issueDate: string;
  dueDate: string;
  status: InvoiceStatus;
  currency: string;
  subtotal: number;
  taxAmount: number;
  totalAmount: number;
  paidAmount: number;
  balanceAmount: number;
  sentAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface Invoice extends InvoiceSummary {
  billingAccount: {
    id: string;
    companyId: string;
    accountType: 'receivable' | 'payable' | 'both';
    accountName: string;
    closingDay: number | null;
    paymentMonthOffset: number;
    paymentDay: number | null;
    invoiceDeliveryMethod: 'email' | 'postal' | 'portal' | 'edi' | 'other';
    isDefault: boolean;
  };
  items: Array<{
    id: string;
    lineNo: number;
    itemType:
      | 'service'
      | 'expense'
      | 'adjustment'
      | 'discount'
      | 'tax_exempt'
      | 'other';
    description: string;
    quantity: number;
    unit: string | null;
    unitPrice: number;
    taxRate: number;
    amount: number;
    taxAmount: number;
    workLogId: string | null;
    displayOrder: number;
  }>;
  payments: Array<{
    id: string;
    paymentType: 'receipt' | 'payment' | 'refund' | 'offset' | 'other';
    paymentDate: string;
    amount: number;
    currency: string;
    paymentMethod: string | null;
    bankFeeAmount: number;
  }>;
  statusHistories: InvoiceStatusHistory[];
}
export interface InvoiceStatusHistory {
  id: string;
  fromStatus: InvoiceStatus | null;
  toStatus: InvoiceStatus;
  changeReason: string | null;
  changedAt: string;
}
export interface InvoiceBillingOption {
  id: string;
  companyId: string;
  companyName: string;
  accountType: 'receivable' | 'payable' | 'both';
  accountName: string;
  closingDay: number | null;
  paymentMonthOffset: number;
  paymentDay: number | null;
  invoiceDeliveryMethod: 'email' | 'postal' | 'portal' | 'edi' | 'other';
  isDefault: boolean;
}
export interface InvoiceOptions {
  billingAccounts: InvoiceBillingOption[];
}
export interface InvoiceItemInput {
  itemType: Invoice['items'][number]['itemType'];
  description: string;
  quantity: number;
  unit: string | null;
  unitPrice: number;
  taxRate: number;
  amount: number;
  taxAmount: number;
  workLogId: string | null;
}
export interface InvoiceInput {
  invoiceNo: string;
  invoiceType: InvoiceType;
  contractId: string | null;
  billingAccountId: string;
  billingPeriodStart: string | null;
  billingPeriodEnd: string | null;
  issueDate: string;
  dueDate: string;
  currency: string;
  items: InvoiceItemInput[];
}
export interface InvoiceStatusTransitionInput {
  status: 'issued' | 'sent' | 'cancelled' | 'void';
  reason: string | null;
}
export interface InvoicePaymentInput {
  paymentType: 'receipt' | 'payment' | 'refund' | 'offset' | 'other';
  paymentDate: string;
  amount: number;
  currency: string;
  paymentMethod:
    | 'bank_transfer'
    | 'cash'
    | 'credit_card'
    | 'direct_debit'
    | 'offset'
    | 'other'
    | null;
  bankFeeAmount: number;
}
export interface InvoicePaymentReversalInput {
  reason: string;
}
export interface InvoiceList {
  items: InvoiceSummary[];
  page: { limit: number; nextCursor: string | null };
}
export interface ListInvoicesQuery {
  q?: string;
  status?: InvoiceStatus;
  invoiceType?: InvoiceType;
  dueFrom?: string;
  dueTo?: string;
  cursor?: string;
  limit?: number;
}

export interface EngagementSummary {
  id: string;
  engagementNo: string;
  contractId: string;
  proposalId: string | null;
  engineerId: string;
  engineerName: string;
  contractTitle: string;
  status: EngagementStatus;
  plannedStartDate: string | null;
  plannedEndDate: string | null;
  actualStartDate: string | null;
  actualEndDate: string | null;
  roleName: string | null;
  workLocation: string | null;
  remoteFrequency: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface EngagementCondition {
  id: string;
  versionNo: number;
  effectiveFrom: string;
  effectiveTo: string | null;
  monthlySalesAmount: number | null;
  monthlyCostAmount: number | null;
  currency: string;
  settlementLowerHours: number | null;
  settlementUpperHours: number | null;
  workLocation: string | null;
  remoteFrequency: string | null;
  notes: string | null;
  createdAt: string;
}
export interface EngagementStatusHistory {
  id: string;
  fromStatus: EngagementStatus | null;
  toStatus: EngagementStatus;
  changeReason: string | null;
  changedAt: string;
}
export interface Engagement extends EngagementSummary {
  previousEngagementId: string | null;
  conditions: EngagementCondition[];
  statusHistories: EngagementStatusHistory[];
}
export interface EngagementConditionInput {
  effectiveFrom: string;
  effectiveTo: string | null;
  monthlySalesAmount: number | null;
  monthlyCostAmount: number | null;
  currency: string;
  settlementLowerHours: number | null;
  settlementUpperHours: number | null;
  notes: string | null;
}
export interface EngagementInput {
  engagementNo: string;
  contractId: string;
  engineerId: string;
  previousEngagementId: string | null;
  plannedStartDate: string;
  plannedEndDate: string | null;
  roleName: string | null;
  workLocation: string | null;
  remoteFrequency: string | null;
  condition: EngagementConditionInput;
}
export interface EngagementStatusTransitionInput {
  status: Exclude<EngagementStatus, 'draft'>;
  reason: string | null;
  actualDate: string | null;
}
export interface EngagementList {
  items: EngagementSummary[];
  page: { limit: number; nextCursor: string | null };
}
export interface ListEngagementsQuery {
  q?: string;
  status?: EngagementStatus;
  cursor?: string;
  limit?: number;
}

export interface Proposal {
  id: string;
  managementNo: string;
  projectPositionId: string;
  engineerId: string;
  destinationCompanyId: string;
  destinationContactId: string | null;
  resumeVersionId: string | null;
  requirementVersionId: string | null;
  proposedUnitPrice: number | null;
  currencyCode: string;
  status: ProposalStatus;
  proposedStartDate: string | null;
  validityDate: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface ProposalInput {
  managementNo: string;
  projectPositionId: string;
  engineerId: string;
  destinationCompanyId: string;
  destinationContactId: string | null;
  resumeVersionId: string | null;
  requirementVersionId: string | null;
  proposedUnitPrice: number | null;
  currencyCode: string;
  proposedStartDate: string | null;
  validityDate: string | null;
}
export interface ProposalStatusTransitionInput {
  status: ProposalStatus;
  reason: string | null;
}
export interface ProposalWinResult {
  proposal: Proposal;
  contractId: string;
  engagementId: string;
  created: boolean;
}
export interface ProposalList {
  items: Proposal[];
  page: { limit: number; nextCursor: string | null };
}
export interface ListProposalsQuery {
  q?: string;
  status?: ProposalStatus;
  cursor?: string;
  limit?: number;
}
export interface Interview {
  id: string;
  proposalId: string;
  proposalManagementNo: string;
  projectPositionId: string;
  engineerId: string;
  interviewRound: number;
  interviewType: InterviewType;
  status: InterviewStatus;
  scheduledStartAt: string | null;
  scheduledEndAt: string | null;
  locationText: string | null;
  meetingUrl: string | null;
  notes: string | null;
  scheduleCandidates: InterviewScheduleCandidate[];
  participants: InterviewParticipant[];
  feedback: InterviewFeedback[];
  outcome: InterviewOutcome | null;
  statusHistory: InterviewStatusHistory[];
  updatedAt: string;
  rowVersion: number;
}
export interface InterviewScheduleCandidate {
  id: string;
  startAt: string;
  endAt: string;
  candidateOrder: number;
}
export interface InterviewScheduleCandidateInput {
  startAt: string;
  endAt: string;
}
export type InterviewParticipantType =
  'engineer' | 'user' | 'company_contact' | 'other';
export type InterviewAttendanceStatus =
  'expected' | 'accepted' | 'declined' | 'attended' | 'absent';
export interface InterviewParticipant {
  id: string;
  participantType: InterviewParticipantType;
  engineerId: string | null;
  userId: string | null;
  companyContactId: string | null;
  displayName: string | null;
  email: string | null;
  roleLabel: string | null;
  attendanceStatus: InterviewAttendanceStatus;
}
export type InterviewParticipantInput = Omit<InterviewParticipant, 'id'>;
export type InterviewRecommendation =
  'strong_yes' | 'yes' | 'hold' | 'no' | 'strong_no';
export interface InterviewFeedback {
  id: string;
  evaluatorUserId: string | null;
  evaluatorContactId: string | null;
  evaluationType: 'internal' | 'customer' | 'engineer';
  overallRating: number | null;
  technicalRating: number | null;
  communicationRating: number | null;
  recommendation: InterviewRecommendation | null;
  comments: string | null;
  submittedAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface InterviewFeedbackInput {
  evaluationType: 'internal';
  overallRating: number | null;
  technicalRating: number | null;
  communicationRating: number | null;
  recommendation: InterviewRecommendation | null;
  comments: string | null;
}
export type InterviewOutcomeCode =
  'pass' | 'fail' | 'hold' | 'withdrawn' | 'pending';
export type InterviewDecisionSource =
  'customer' | 'internal' | 'engineer' | 'system';
export interface InterviewOutcome {
  id: string;
  outcome: InterviewOutcomeCode;
  decidedAt: string | null;
  decisionSource: InterviewDecisionSource | null;
  reason: string | null;
  nextAction: string | null;
  nextActionDueAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface InterviewOutcomeInput {
  outcome: InterviewOutcomeCode;
  decidedAt: string | null;
  decisionSource: InterviewDecisionSource;
  reason: string | null;
  nextAction: string | null;
  nextActionDueAt: string | null;
}
export interface InterviewStatusHistory {
  id: string;
  fromStatus: InterviewStatus | null;
  toStatus: InterviewStatus;
  changedAt: string;
  reason: string | null;
}
export interface InterviewResultInput {
  status: 'completed' | 'cancelled' | 'no_show';
  reason: string | null;
  participants: InterviewParticipantInput[];
  feedback: InterviewFeedbackInput | null;
  outcome: InterviewOutcomeInput | null;
}
export interface InterviewInput {
  proposalId: string;
  interviewRound: number;
  interviewType: InterviewType;
  status: 'tentative' | 'scheduled';
  scheduledStartAt: string | null;
  scheduledEndAt: string | null;
  locationText: string | null;
  meetingUrl: string | null;
  notes: string | null;
  scheduleCandidates: InterviewScheduleCandidateInput[];
}
export interface InterviewList {
  items: Interview[];
  page: { limit: number; nextCursor: string | null };
}
export interface ListInterviewsQuery {
  q?: string;
  status?: InterviewStatus;
  cursor?: string;
  limit?: number;
}
