// This file is generated by scripts/generate-api-client.mjs.
// Do not edit it directly. Run pnpm client:generate after changing OpenAPI.

export type ProjectStatus =
  'draft' | 'open' | 'on_hold' | 'closed' | 'cancelled';
export type RecruitmentStatus = 'recruiting' | 'paused' | 'filled' | 'ended';
export type CompanyStatus = 'prospect' | 'active' | 'inactive' | 'blocked';
export type ContactStatus = 'active' | 'inactive' | 'left_company' | 'unknown';
export type EngineerStatus =
  'candidate' | 'active' | 'inactive' | 'retired' | 'blocked';
export type AvailabilityStatus =
  'unknown' | 'available' | 'proposed' | 'engaged' | 'unavailable';
export type ProposalStatus =
  | 'draft'
  | 'pending_approval'
  | 'approved'
  | 'sent'
  | 'interview_requested'
  | 'interviewing'
  | 'offered'
  | 'won'
  | 'lost'
  | 'withdrawn'
  | 'cancelled';
export type InterviewType = 'online' | 'onsite' | 'phone' | 'other';
export type InterviewStatus =
  'tentative' | 'scheduled' | 'completed' | 'cancelled' | 'no_show';
export type ContractType =
  | 'ses'
  | 'dispatch'
  | 'subcontract'
  | 'quasi_mandate'
  | 'fixed_price'
  | 'other';
export type ContractStatus =
  | 'draft'
  | 'review'
  | 'active'
  | 'suspended'
  | 'expired'
  | 'terminated'
  | 'cancelled';

export interface AuthContext {
  requiresMfa: boolean;
}

export interface Engineer {
  id: string;
  managementNo: string;
  familyName: string;
  givenName: string;
  displayName: string | null;
  status: EngineerStatus;
  availabilityStatus: AvailabilityStatus;
  availableFrom: string | null;
  nearestStation: string | null;
  summary: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface EngineerList {
  items: Engineer[];
  page: { limit: number; nextCursor: string | null };
}
export interface EngineerInput {
  managementNo: string;
  familyName: string;
  givenName: string;
  displayName: string | null;
  status: EngineerStatus;
  availabilityStatus: AvailabilityStatus;
  availableFrom: string | null;
  nearestStation: string | null;
  summary: string | null;
}
export interface EngineerAuditEvent {
  id: string;
  occurredAt: string;
  actorUserId: string | null;
  action: string;
  requestId: string | null;
}
export interface EngineerAuditList {
  items: EngineerAuditEvent[];
}
export type EngineerGender = 'male' | 'female' | 'other' | 'undisclosed';
export interface EngineerPrivateDetail {
  engineerId: string;
  birthDate: string | null;
  gender: EngineerGender | null;
  personalEmail: string | null;
  phone: string | null;
  postalCode: string | null;
  prefecture: string | null;
  city: string | null;
  addressLine: string | null;
  emergencyContact: string | null;
  notes: string | null;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerPrivateInput = Omit<
  EngineerPrivateDetail,
  'engineerId' | 'updatedAt' | 'rowVersion'
>;
export type EngineerAffiliationType =
  'employee' | 'freelance' | 'partner_employee' | 'subcontractor' | 'other';
export interface EngineerAffiliation {
  id: string;
  engineerId: string;
  companyId: string;
  affiliationType: EngineerAffiliationType;
  contractType: string | null;
  startDate: string;
  endDate: string | null;
  isPrimary: boolean;
  notes: string | null;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerAffiliationInput = Omit<
  EngineerAffiliation,
  'id' | 'engineerId' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerAffiliationList {
  items: EngineerAffiliation[];
}
export type RemotePreference = 'onsite' | 'hybrid' | 'remote' | 'flexible';
export interface EngineerPreference {
  id: string;
  engineerId: string;
  effectiveFrom: string;
  effectiveTo: string | null;
  desiredRateMin: number | null;
  desiredRateMax: number | null;
  currencyCode: string;
  remotePreference: RemotePreference;
  weeklyDaysMin: number | null;
  weeklyDaysMax: number | null;
  overtimeLimitHours: number | null;
  availableFrom: string | null;
  notes: string | null;
  locations: string[];
  contractTypes: string[];
  updatedAt: string;
  rowVersion: number;
}
export type EngineerPreferenceInput = Omit<
  EngineerPreference,
  'id' | 'engineerId' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerPreferenceList {
  items: EngineerPreference[];
}
export interface EngineerCareerHistory {
  id: string;
  engineerId: string;
  projectName: string;
  clientName: string | null;
  roleName: string | null;
  industry: string | null;
  overview: string | null;
  responsibilities: string | null;
  achievements: string | null;
  teamSize: number | null;
  startedOn: string | null;
  endedOn: string | null;
  displayOrder: number;
  sourceResumeVersionId: string | null;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerCareerHistoryInput = Omit<
  EngineerCareerHistory,
  'id' | 'engineerId' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerCareerHistoryList {
  items: EngineerCareerHistory[];
}
export interface EngineerResumeVersion {
  id: string;
  versionNo: number;
  fileStoragePath: string | null;
  originalFileName: string | null;
  mimeType: string | null;
  fileSizeBytes: number | null;
  fileChecksum: string | null;
  sourceType: string;
  createdAt: string;
}
export interface EngineerResume {
  id: string;
  engineerId: string;
  title: string;
  resumeStatus: string;
  currentVersionId: string | null;
  updatedAt: string;
  rowVersion: number;
  versions: EngineerResumeVersion[];
}
export interface EngineerResumeVersionInput {
  title: string;
  resumeStatus: string;
  fileStoragePath: string | null;
  originalFileName: string | null;
  mimeType: string | null;
  fileSizeBytes: number | null;
  fileChecksum: string | null;
  sourceType: string;
}
export interface EngineerResumeList {
  items: EngineerResume[];
}
export interface EngineerSkill {
  id: string;
  engineerId: string;
  skillId: string;
  skillName: string;
  experienceMonths: number | null;
  proficiencyLevel: number | null;
  lastUsedOn: string | null;
  evidenceType: string | null;
  evidenceNote: string | null;
  verificationStatus: string;
  isPrimary: boolean;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerSkillInput = Omit<
  EngineerSkill,
  'id' | 'engineerId' | 'skillName' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerSkillList {
  items: EngineerSkill[];
}
export interface EngineerQualification {
  id: string;
  engineerId: string;
  name: string;
  issuer: string | null;
  credentialId: string | null;
  acquiredOn: string | null;
  expiresOn: string | null;
  notes: string | null;
  updatedAt: string;
  rowVersion: number;
}
export type EngineerQualificationInput = Omit<
  EngineerQualification,
  'id' | 'engineerId' | 'updatedAt' | 'rowVersion'
>;
export interface EngineerQualificationList {
  items: EngineerQualification[];
}
export interface ListEngineersQuery {
  q?: string;
  status?: EngineerStatus;
  availabilityStatus?: AvailabilityStatus;
  cursor?: string;
  limit?: number;
}

export interface Company {
  id: string;
  managementNo: string;
  legalName: string;
  displayName: string | null;
  corporateNumber: string | null;
  postalCode: string | null;
  prefecture: string | null;
  city: string | null;
  addressLine: string | null;
  websiteUrl: string | null;
  representativeName: string | null;
  status: CompanyStatus;
  updatedAt: string;
  rowVersion: number;
}

export interface CompanyList {
  items: Company[];
  page: { limit: number; nextCursor: string | null };
}

export interface CompanyAuditEvent {
  id: string;
  occurredAt: string;
  actorUserId: string | null;
  action: string;
  requestId: string | null;
}

export interface CompanyAuditList {
  items: CompanyAuditEvent[];
}

export interface CompanyInput {
  managementNo: string;
  legalName: string;
  displayName: string | null;
  corporateNumber: string | null;
  postalCode: string | null;
  prefecture: string | null;
  city: string | null;
  addressLine: string | null;
  websiteUrl: string | null;
  representativeName: string | null;
  status: CompanyStatus;
}

export interface ListCompaniesQuery {
  q?: string;
  status?: CompanyStatus;
  cursor?: string;
  limit?: number;
}

export interface CompanyContact {
  id: string;
  companyId: string;
  managementNo: string;
  familyName: string;
  givenName: string | null;
  departmentName: string | null;
  positionTitle: string | null;
  email: string | null;
  phone: string | null;
  mobilePhone: string | null;
  isPrimary: boolean;
  status: ContactStatus;
  updatedAt: string;
  rowVersion: number;
}
export interface CompanyContactList {
  items: CompanyContact[];
  page: { limit: number; nextCursor: string | null };
}
export interface CompanyContactAuditEvent {
  id: string;
  occurredAt: string;
  actorUserId: string | null;
  action: string;
  requestId: string | null;
}
export interface CompanyContactAuditList {
  items: CompanyContactAuditEvent[];
}
export interface CompanyContactInput {
  companyId: string;
  managementNo: string;
  familyName: string;
  givenName: string | null;
  departmentName: string | null;
  positionTitle: string | null;
  email: string | null;
  phone: string | null;
  mobilePhone: string | null;
  isPrimary: boolean;
  status: ContactStatus;
}
export interface ListCompanyContactsQuery {
  companyId?: string;
  q?: string;
  status?: ContactStatus;
  cursor?: string;
  limit?: number;
}

export interface Project {
  id: string;
  managementNo: string;
  projectName: string;
  summary: string | null;
  projectStatus: ProjectStatus;
  recruitmentStatus: RecruitmentStatus;
  plannedStartOn: string | null;
  plannedEndOn: string | null;
  updatedAt: string;
  rowVersion: number;
}

export interface ProjectList {
  items: Project[];
  page: { limit: number; nextCursor: string | null };
}

export interface ProjectAuditEvent {
  id: string;
  occurredAt: string;
  actorUserId: string | null;
  action: string;
  requestId: string | null;
}

export interface ProjectAuditList {
  items: ProjectAuditEvent[];
}

export interface ProjectInput {
  managementNo: string;
  projectName: string;
  summary: string | null;
  projectStatus: ProjectStatus;
  recruitmentStatus: RecruitmentStatus;
  plannedStartOn: string | null;
  plannedEndOn: string | null;
}

export interface ApiErrorBody {
  error: { code: string; message: string; requestId: string };
}

export interface ListProjectsQuery {
  q?: string;
  status?: ProjectStatus;
  recruitmentStatus?: RecruitmentStatus;
  cursor?: string;
  limit?: number;
}

export interface ContractSummary {
  id: string;
  contractNo: string;
  projectId: string | null;
  proposalId: string | null;
  engineerId: string | null;
  contractType: ContractType;
  status: ContractStatus;
  title: string;
  startDate: string;
  endDate: string | null;
  autoRenew: boolean;
  currency: string;
  updatedAt: string;
  rowVersion: number;
}
export type ContractPartyRole =
  | 'customer'
  | 'supplier'
  | 'employer'
  | 'end_client'
  | 'prime_contractor'
  | 'subcontractor'
  | 'other';
export type ContractBillingRole = 'bill_to' | 'pay_to' | 'none';
export interface ContractParty {
  id: string;
  companyId: string;
  contactId: string | null;
  partyRole: ContractPartyRole;
  billingRole: ContractBillingRole | null;
  isPrimary: boolean;
}
export interface ContractVersion {
  id: string;
  versionNo: number;
  effectiveFrom: string;
  effectiveTo: string | null;
  changeSummary: string | null;
  approvedAt: string | null;
  createdAt: string;
}
export type ContractWorkLogStatus =
  'draft' | 'submitted' | 'approved' | 'rejected' | 'locked';
export interface ContractWorkLog {
  id: string;
  engineerId: string;
  workMonth: string;
  status: ContractWorkLogStatus;
  scheduledDays: number | null;
  actualDays: number | null;
  scheduledHours: number | null;
  actualHours: number | null;
  overtimeHours: number;
  absenceHours: number;
  customerApprovedAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface Contract extends ContractSummary {
  monthlyAmount: number | null;
  hourlyAmount: number | null;
  settlementLowerHours: number | null;
  settlementUpperHours: number | null;
  paymentTerms: string | null;
  notes: string | null;
  parties: ContractParty[];
  versions: ContractVersion[];
  workLogs: ContractWorkLog[];
}
export interface ContractList {
  items: ContractSummary[];
  page: { limit: number; nextCursor: string | null };
}
export interface ListContractsQuery {
  q?: string;
  status?: ContractStatus;
  cursor?: string;
  limit?: number;
}

export interface Proposal {
  id: string;
  managementNo: string;
  projectPositionId: string;
  engineerId: string;
  destinationCompanyId: string;
  destinationContactId: string | null;
  resumeVersionId: string | null;
  requirementVersionId: string | null;
  proposedUnitPrice: number | null;
  currencyCode: string;
  status: ProposalStatus;
  proposedStartDate: string | null;
  validityDate: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface ProposalInput {
  managementNo: string;
  projectPositionId: string;
  engineerId: string;
  destinationCompanyId: string;
  destinationContactId: string | null;
  resumeVersionId: string | null;
  requirementVersionId: string | null;
  proposedUnitPrice: number | null;
  currencyCode: string;
  proposedStartDate: string | null;
  validityDate: string | null;
}
export interface ProposalStatusTransitionInput {
  status: ProposalStatus;
  reason: string | null;
}
export interface ProposalList {
  items: Proposal[];
  page: { limit: number; nextCursor: string | null };
}
export interface ListProposalsQuery {
  q?: string;
  status?: ProposalStatus;
  cursor?: string;
  limit?: number;
}
export interface Interview {
  id: string;
  proposalId: string;
  proposalManagementNo: string;
  projectPositionId: string;
  engineerId: string;
  interviewRound: number;
  interviewType: InterviewType;
  status: InterviewStatus;
  scheduledStartAt: string | null;
  scheduledEndAt: string | null;
  locationText: string | null;
  meetingUrl: string | null;
  notes: string | null;
  scheduleCandidates: InterviewScheduleCandidate[];
  participants: InterviewParticipant[];
  feedback: InterviewFeedback[];
  outcome: InterviewOutcome | null;
  statusHistory: InterviewStatusHistory[];
  updatedAt: string;
  rowVersion: number;
}
export interface InterviewScheduleCandidate {
  id: string;
  startAt: string;
  endAt: string;
  candidateOrder: number;
}
export interface InterviewScheduleCandidateInput {
  startAt: string;
  endAt: string;
}
export type InterviewParticipantType =
  'engineer' | 'user' | 'company_contact' | 'other';
export type InterviewAttendanceStatus =
  'expected' | 'accepted' | 'declined' | 'attended' | 'absent';
export interface InterviewParticipant {
  id: string;
  participantType: InterviewParticipantType;
  engineerId: string | null;
  userId: string | null;
  companyContactId: string | null;
  displayName: string | null;
  email: string | null;
  roleLabel: string | null;
  attendanceStatus: InterviewAttendanceStatus;
}
export type InterviewParticipantInput = Omit<InterviewParticipant, 'id'>;
export type InterviewRecommendation =
  'strong_yes' | 'yes' | 'hold' | 'no' | 'strong_no';
export interface InterviewFeedback {
  id: string;
  evaluatorUserId: string | null;
  evaluatorContactId: string | null;
  evaluationType: 'internal' | 'customer' | 'engineer';
  overallRating: number | null;
  technicalRating: number | null;
  communicationRating: number | null;
  recommendation: InterviewRecommendation | null;
  comments: string | null;
  submittedAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface InterviewFeedbackInput {
  evaluationType: 'internal';
  overallRating: number | null;
  technicalRating: number | null;
  communicationRating: number | null;
  recommendation: InterviewRecommendation | null;
  comments: string | null;
}
export type InterviewOutcomeCode =
  'pass' | 'fail' | 'hold' | 'withdrawn' | 'pending';
export type InterviewDecisionSource =
  'customer' | 'internal' | 'engineer' | 'system';
export interface InterviewOutcome {
  id: string;
  outcome: InterviewOutcomeCode;
  decidedAt: string | null;
  decisionSource: InterviewDecisionSource | null;
  reason: string | null;
  nextAction: string | null;
  nextActionDueAt: string | null;
  updatedAt: string;
  rowVersion: number;
}
export interface InterviewOutcomeInput {
  outcome: InterviewOutcomeCode;
  decidedAt: string | null;
  decisionSource: InterviewDecisionSource;
  reason: string | null;
  nextAction: string | null;
  nextActionDueAt: string | null;
}
export interface InterviewStatusHistory {
  id: string;
  fromStatus: InterviewStatus | null;
  toStatus: InterviewStatus;
  changedAt: string;
  reason: string | null;
}
export interface InterviewResultInput {
  status: 'completed' | 'cancelled' | 'no_show';
  reason: string | null;
  participants: InterviewParticipantInput[];
  feedback: InterviewFeedbackInput | null;
  outcome: InterviewOutcomeInput | null;
}
export interface InterviewInput {
  proposalId: string;
  interviewRound: number;
  interviewType: InterviewType;
  status: 'tentative' | 'scheduled';
  scheduledStartAt: string | null;
  scheduledEndAt: string | null;
  locationText: string | null;
  meetingUrl: string | null;
  notes: string | null;
  scheduleCandidates: InterviewScheduleCandidateInput[];
}
export interface InterviewList {
  items: Interview[];
  page: { limit: number; nextCursor: string | null };
}
export interface ListInterviewsQuery {
  q?: string;
  status?: InterviewStatus;
  cursor?: string;
  limit?: number;
}
